export const PROPERTY_ADD: string = "PROPERTY_ADD"
export const PROPERTY_EDIT: string = "PROPERTY_EDIT"
export const ASSETS_PROPERTY_INCOME: string = "ASSETS_PROPERTY_INCOME"
export const ASSETS_PROPERTY_DELETE: string = "ASSETS_PROPERTY_ADD"
export const ASSETS_PROPERTY_INVENTORY: string = "ASSETS_PROPERTY_INVENTORY"

export const LIABILITIES_PROPERTY_ADD: string = "LIABILITIES_PROPERTY_ADD"
export const LIABILITIES_PROPERTY_EDIT: string = "LIABILITIES_PROPERTY_EDIT"
export const LIABILITIES_PROPERTY_INCOME: string = "LIABILITIES_PROPERTY_INCOME"
export const LIABILITIES_PROPERTY_INVENTORY: string = "LIABILITIES_PROPERTY_INVENTORY"

export const ASSETS_TRANSPORT_ADD: string = "ASSETS_TRANSPORT_ADD"
export const ASSETS_TRANSPORT_DELETE: string = "ASSETS_TRANSPORT_DELETE"
export const ASSETS_TRANSPORT_EDIT: string = "ASSETS_TRANSPORT_EDIT"
export const ASSETS_TRANSPORT_INCOME: string = "ASSETS_TRANSPORT_INCOME"

export const ASSETS_BUSINESS_ADD: string = "ASSETS_BUSINESS_ADD"
export const ASSETS_BUSINESS_EDIT: string = "ASSETS_BUSINESS_EDIT"
export const ASSETS_BUSINESS_INCOME: string = "ASSETS_BUSINESS_INCOME"
export const ASSETS_BUSINESS_DELETE: string = "ASSETS_BUSINESS_DELETE"
export const ASSETS_BUSINESS_INVENTORY: string = "ASSETS_BUSINESS_INVENTORY"

export const LIABILITIES_TRANSPORT_DELETE: string = "LIABILITIES_TRANSPORT_DELETE"
export const LIABILITIES_TRANSPORT_EDIT: string = "LIABILITIES_TRANSPORT_EDIT"
export const LIABILITIES_TRANSPORT_ADD: string = "LIABILITIES_TRANSPORT_ADD"
export const LIABILITIES_TRANSPORT_INCOME: string = "LIABILITIES_TRANSPORT_INCOME"


export const LIABILITIES_PROPERTY_DELETE: string = "LIABILITIES_PROPERTY_DELETE"

export const LIABILITIES_LOANS_ADD: string = "LIABILITIES_LOANS_ADD"
export const LIABILITIES_LOANS_DELETE: string = "LIABILITIES_LOANS_DELETE"

export const SHOW_PLANNER_ADD: string = "LIABILITIES_LOANS_ADD"

export const LIABILITIES_PROJECT_DELETE: string = "LIABILITIES_PROJECT_DELETE"
export const LIABILITIES_PROJECT_EDIT: string = "LIABILITIES_PROJECT_EDIT"
export const LIABILITIES_PROJECT_ADD: string = "LIABILITIES_PROJECT_ADD"

export const BALANCE_ITEM_DELETE: string = "BALANCE_ITEM_DELETE"
export const BALANCE_ITEM_EDIT: string = "BALANCE_ITEM_EDIT"
export const BALANCE_ITEM_ADD: string = "BALANCE_ITEM_ADD"